### ISSUE TITLE
Error message: Forbidden

### ISSUE THREAD

**Issue by szogun1910** [Forge-Media/teamspeak-bot#4]
@Forge-Media 
Hey, can you help me with the app? Unfortunately, my stories get some mistakes

`Game ranks: Connecting to Teamspeak
Loading plugins...
Loaded: joinMe
Loaded: help
Loaded: registerCSGO
Game ranks: Subscribed to Private Teamspeak Text Messages
Game ranks: Teamspeak connection is Ready
Game ranks: Loading Steam Intergration...
Error Type: 403
Error message: Forbidden
TypeError: Cannot read property 'name' of null
    at riotHelper.init (/home/ranks/helpers/riotHelper.js:36:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jarvis-teamspeak-bot@0.9.3 jarvis: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jarvis-teamspeak-bot@0.9.3 jarvis script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2020-12-24T20_33_44_426Z-debug.log
`

**Comment by Forge-Media** [comment]
I think the general problem here is that even if you disable the `!registerLOL` plugin within the config file.
```javascript
plugins: {
  registerLOL: false,
},
```
The app will still try to load the `riotHelper` class. Which requires a valid Riot Games API key in your config file.

I think this COULD be solved within **jarvis.js** as follows: 
```javascript
// Once Teamspeak 3 connection is established Steam connection
if (this.config.integrations.steamHelper.config) {
  this.steam = new steamHelper(this.config.integrations.steamHelper.config, this.name, this.firebase.db, this.ts);
}
// Once Teamspeak 3 connection is established Riot-API connection
if (this.config.integrations.riotHelper.config.api_key) {
  this.riot = new riotHelper(this.config.integrations.riotHelper.config, this.name, this.firebase.db);
}
```

The  `TypeError: Cannot read property 'name' of null at riotHelper.init` 
Also suggests that `config.settings.nickname` is empty?

**Comment by Forge-Media** [comment]
**The bot at present has a number of problems due to changes to ts3-nodejs-library and node-csgo which I'm working to resolve first. The most pressing is a major bug with the CSGO integration which causes the bot to crash.**

I've requested support on this here: https://gitter.im/joshuaferrara/node-csgo

Until these problems are resolved, Jarvis Bot does not really work. I'm hoping to fix most of these up in the next week or so.
